"""empty message

Revision ID: 35e2ea0bf328
Revises: 3579a31f801f
Create Date: 2021-02-21 14:21:37.989084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35e2ea0bf328'
down_revision = '3579a31f801f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('months', sa.Column('number', sa.Integer(), nullable=False))
    op.drop_column('months', 'month_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('months', sa.Column('month_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('months', 'number')
    # ### end Alembic commands ###
